version: "3.9"

services:
  server:
    build:
      context: .
    environment:
      DATABASE_URL: "jdbc:postgresql://db:5432/sharedcard"
      SERVER_PORT: "8081"
      LOGIN: "postgres"
      PASSWORD: "qwe321loi"
    ports:
      - "8081:8081"
    depends_on:
      cats-db-clswk:
        condition: service_started
       	
  db:
    image: postgres:latest 
    environment:
      ​​POSTGRES_DB: "sharedcard"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwe321loi"
