scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'db'
    static_configs:
      - targets: ['db:5432']
  - job_name: 'server'
    static_configs:
      - targets: [ 'server:8081' ]